[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.128.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Optional: redirect /admin/ to the CMS app
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
